balckowl/portolio-new-3

- src/app/(pages)/mypage/page.tsx
- src/app/components/mypage/post/postList.tsx
- src/data/post.ts
- src/lib/prisma/db.ts
> Create data-fetch functions.

- package-lock.json
- package.json
- src/app/(pages)/posts/[id]/page.tsx
- src/app/components/posts/article.tsx
- src/components/ui/tabs.tsx
> feat: create-detail

- package-lock.json
- package.json
- src/app/(pages)/[userId]/edit/page.tsx
- src/app/components/editProfile/form.tsx
- src/components/ui/accordion.tsx
- src/components/ui/form.tsx
- src/components/ui/input.tsx
- src/components/ui/label.tsx
- src/components/ui/textarea.tsx
プロフィール編集画面について、フロントの部分だけ移行しました
> feat: create-profile-change-form

- src/app/(pages)/posts/create/page.tsx
- src/app/components/posts/editor.tsx
> feat: create-article-editor

- src/data/user.ts
> User data fetch.

- package-lock.json
- package.json
- src/app/(pages)/posts/create/page.tsx
- src/app/components/posts/editor.tsx
- src/components/ui/dialog.tsx
- src/components/ui/popover.tsx
記事の投稿ページで実際にデータベースに送信が行えるようにしました。
> feat: submit post

- src/app/components/mypage/post/post.tsx
- src/app/components/mypage/post/postList.tsx
- src/app/components/posts/editor.tsx
> chore: link to post

- src/app/components/posts/article.tsx
- src/app/components/posts/editor.tsx
・削除機能を付けました
・前回のプッシュで間違って上書きしてしまった部分を直しました
> feat: delete logic

- src/app/components/layouts/footer.tsx
- src/app/components/layouts/header.tsx
- src/app/components/posts/article.tsx
- src/app/layout.tsx
> Header and footer logic.

- package-lock.json
- package.json
- src/app/components/mypage/userPorfile.tsx
> Get userdata from db.

- src/app/components/posts/article.tsx
> feat: update logic

- src/app/(pages)/posts/[id]/page.tsx
- src/app/components/posts/article.tsx
- src/data/post.ts
新しいコメントを追加する部分のロジックを作りました
少し型エラーが起きています
> feat: create-new-comment

- src/app/(pages)/mypage/edit/page.tsx
- src/app/components/editProfile/form.tsx
- src/app/components/mypage/post/post.tsx
- src/app/components/posts/article.tsx
- src/app/components/posts/picker.tsx
> Updated Dark Mode

- package-lock.json
- package.json
- src/app/components/home/arrowDown.tsx
- src/app/components/home/hero.tsx
- src/app/components/home/start.tsx
- src/app/components/layouts/header.tsx
- src/components/ui/sheet.tsx
> Edited top page

- src/app/(pages)/[userId]/edit/page.tsx
- src/app/(pages)/[userId]/page.tsx
- src/app/(pages)/posts/[id]/page.tsx
- src/app/(pages)/posts/create/page.tsx
> Create page block.

- src/app/(pages)/auth/login/page.tsx
> Create page block

- src/app/components/mypage/post/post.tsx
- src/app/components/mypage/post/postList.tsx
- src/app/components/posts/article.tsx
- src/app/components/posts/css/editer.css
- src/app/components/posts/editor.tsx
> Changed markdown style

- src/app/components/posts/article.tsx
> Inserted alert popup when selected delete

- src/app/components/home/hero.tsx
- src/app/components/home/start.tsx
- src/app/components/layouts/header.tsx
- src/app/components/mypage/userPorfile.tsx
> Fixed button that didn't go properly

- src/app/components/auth/signInWithGithubBtn.tsx
- src/app/components/editProfile/form.tsx
- src/app/components/posts/article.tsx
- src/app/components/posts/editor.tsx
> BaseUrl-to-env,

- src/app/components/auth/sessionProvider.tsx
- src/app/layout.tsx
> Restore darkmode
